2020-09-23 17:33:27,247 ERROR: Exception on /edit_profile [POST] [in c:\users\1\web_app1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\web_app5\word_collection\app\routes.py", line 84, in edit_profile
    dictionary = Dictionary(user_id = currrent_user.id, language_id = form.languages.data)
NameError: name 'currrent_user' is not defined
2020-09-23 17:34:31,047 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-23 17:37:10,456 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-23 17:38:20,374 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-23 17:39:01,621 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:07:18,302 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:07:27,234 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:07:34,985 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:08:27,099 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:56:36,327 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:58:04,238 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:58:36,825 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:58:56,492 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 17:59:32,447 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:16:50,149 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:19:02,431 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:20:17,041 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:20:41,224 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:21:40,826 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:26:50,659 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:28:38,326 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:30:30,983 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:34:07,120 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:39:25,652 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:40:08,831 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:41:02,400 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:41:58,141 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:42:31,089 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:45:08,349 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:45:33,903 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:46:15,739 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:49:18,139 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:51:28,417 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:54:34,899 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 18:58:06,463 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 19:28:07,023 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:33]
2020-09-24 19:48:42,332 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:03:37,564 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:06:41,253 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:12:04,908 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:16:17,712 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:16:47,347 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:17:01,873 INFO: Lang startup [in C:\Users\1\web_app5\word_collection\app\__init__.py:35]
2020-09-24 20:17:30,936 ERROR: Exception on /... [GET] [in c:\users\1\web_app1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "c:\users\1\web_app1\venv\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "C:\Users\1\web_app5\word_collection\app\errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
